### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Attempted to register a second handler for 'get-all-shortcuts'

### ISSUE THREAD

**Issue by Nothing-Works** [manojVivek/responsively-app#184]
This is only happening on `macOS` as far as I know.

# How to reproduce.

1. Use the current `master` branch code, `cd desktop-app` and `npm run dev`.

2. **Close the app** by clicking the red x.
<img width="80" alt="Screen Shot 2020-06-10 at 23 20 07" src="https://user-images.githubusercontent.com/18606648/84262191-45dd3300-ab71-11ea-8ffc-6463898435bd.png">

3. And then open the app by clicking the icon from the mac dock.
<img width="85" alt="Screen Shot 2020-06-10 at 23 24 25" src="https://user-images.githubusercontent.com/18606648/84262336-8e94ec00-ab71-11ea-8538-350a2dedc988.png">

And this is what I get from the console.

`(node:34685) UnhandledPromiseRejectionWarning: Error: Attempted to register a second handler for 'get-all-shortcuts'
    at IpcMainImpl.handle (electron/js2c/browser_init.js:5868:23)
    at initMainShortcutManager (/Users/andysong/Projects/responsively-app/desktop-app/app/shortcut-manager/main-shortcut-manager.js:52:13)
    at createWindow (/Users/andysong/Projects/responsively-app/desktop-app/app/main.dev.js:196:3)`

At the beginning, I thought this is related to my previous pr https://github.com/manojVivek/responsively-app/pull/174 but after reading the error message, I think this is not the case. It's from https://github.com/manojVivek/responsively-app/pull/168 I think.

So, if someone can take a look at this would be great.

**Comment by jjavierdguezas** [comment]
@Nothing-Works  right now we are not using that channel for anything so we can get rid of it, or just call `ipcMain.removeHandler(GET_ALL_CHANNEL)` before [this line](https://github.com/manojVivek/responsively-app/blob/5598529cfb06ac71f719fd97ab4b2c5ba1d9cd33/desktop-app/app/shortcut-manager/main-shortcut-manager.js#L52) in [main-shortcut-manager.js](https://github.com/manojVivek/responsively-app/blob/master/desktop-app/app/shortcut-manager/main-shortcut-manager.js) to ensure that there is onle one handler,

But what is really strange is that after closing the app, the `ipcMain` object continues to retain its state 🤔, maybe the app wasn't really closed? Maybe there was multiple instances running?
